### ISSUE TITLE
Use Github Actions [LEARN]

### ISSUE THREAD

**Issue by SaumickPradhan** [EECE3093C/team-project-cyber-tech#38]

**Comment by NehangPatel23** [comment]
UPDATE: Read the documentation for GitHub Actions at [this website](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions), and implement it in the repository.

**Comment by NehangPatel23** [comment]
@SaumickPradhan @Dhyey-Patel28 @naachiketdighe @Avalon047 any ideas as to what the GitHub Action is supposed to do? I do have a workflow set that runs every time there is a push to the branch.
